### PR TITLE
Everything of value from Civclassic fork

### PR DESCRIPTION
**Pull request by Maxopoly**
Teal copied a bunch of Humbug stuff into the Civclassic fork of SAH, this is a cleaned up version of that.

It adds the ability to enable/disable:

- Minecart TP
- 1.7 Obsidian generator
- Personal death messages
- Preventing trees from wrapping around the world (y 255 --> 0)
- Humbugs pearl fixes regarding where you can (not) pearl in regards to half blocks
- Sanity checks regarding sign length
- Ender chests
- Skeleton horse traps
- Changing spawner types with spawn eggs
- Villager trading
- Ender man block griefing
- Wither block griefing
- Falling through bedrock (will trigger a minecart tp)
- Prevent placement of certain blocks

### CODE REVIEW

**Comment by Maxopoly** [comment]
Also I want to note that the cobertura-maven plugin you have in the pom sucks. It somehow fails to do the goal `clean` for me

```
[INFO] ------------------------------------------------------------------------
[INFO] Building SimpleAdminHacks 1.2.4
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ SimpleAdminHacks ---
[INFO] Deleting /home/max/eclipse/cpp-photon/java/SimpleAdminHacks/target
[INFO] 
[INFO] --- cobertura-maven-plugin:2.7:clean (default) @ SimpleAdminHacks ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.480 s
[INFO] Finished at: 2019-03-04T20:24:57+01:00
[INFO] Final Memory: 8M/30M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:cobertura-maven-plugin:2.7:clean (default) on project SimpleAdminHacks: Execution default of goal org.codehaus.mojo:cobertura-maven-plugin:2.7:clean failed: Plugin org.codehaus.mojo:cobertura-maven-plugin:2.7 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:0 at specified path /usr/lib/jvm/java-10-oracle/../lib/tools.jar -> [Help 1]
[ERROR] 
```

**Comment by ProgrammerDan** [comment]
that's kind of hilarious. I'll check and see if there is any reason for
that...  never had any trouble that I recall

**Comment by Maxopoly** [comment]
This should be merged

**Comment by ProgrammerDan** [comment]
yes

theoretically was getting buildserv set up to autobuild, lost the thread on
it.

**Comment by Maxopoly** [comment]
bump

**Comment by ProgrammerDan** [comment]
whole file diffs make me cringe, but visually appears to be no destructive or hidden changes.

Ofc I will weep for my bots and crazycrates, but for broader consumption best not to have those.

**Comment by Maxopoly** [comment]
Seemingly Teal reformatted a lot of it at some point for whatever reason. 

Not sure I understand your comment, do you want me to undo that formatting or readd CrazyCrates or what?

**Comment by ProgrammerDan** [comment]
Nah, no action needed, my comment was just a comment.

**Comment by ProgrammerDan** [comment]
ok to build

**Pull request merged**
